import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  en: {
    // Topbar & Navigation
    brandName: "Library Management",
    brandSubtitle: "Smart Knowledge & Circulation Portal",
    brandShort: "Library Portal",
    toggleNav: "Toggle Navigation",
    askAIAssistant: "Ask AI Assistant",
    notifications: "Notifications",
    markAllRead: "Mark all as read",
    noNewNotifications: "No new notifications",
    signIn: "Sign In",
    joinLibrary: "Join Library",
    signOut: "Sign Out",
    welcomeBack: "Welcome Back",
    english: "English",
    tamil: "தமிழ்",

    // Roles & Badges
    ADMIN: "Admin",
    LIBRARIAN: "Librarian",
    STUDENT: "Student",
    AVAILABLE: "Available",
    ISSUED: "Issued",
    OVERDUE: "Overdue",
    RETURNED: "Returned",
    RESERVED: "Reserved",
    WAITING: "In Queue",
    READY: "Ready for Pickup",
    CANCELLED: "Cancelled",
    OUT_OF_STOCK: "Out of Stock",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    PENDING: "Pending",
    APPROVED: "Approved",
    PURCHASED: "Purchased",
    REJECTED: "Rejected",

    // Sidebar Menus
    navHome: "Home / Showcase",
    navCatalog: "Book Catalog",
    navRecommendations: "AI Recommendations",
    navAssistant: "AI Smart Assistant",
    navMyReading: "My Reading & Goals",
    navWishlist: "Wishlist & Bookmarks",
    navReservations: "My Reservations",
    navRequests: "Book Requests & Votes",
    navFacilities: "Reserve Study Seat",
    navProfile: "My Profile",
    navAdminDashboard: "Admin Dashboard",
    navCirculationHub: "Circulation Hub",
    navBookMgmt: "Book Management",
    navOCRScanner: "OCR Book Scanner",
    navCirculation: "Issue / Return / Renew",
    navFines: "Overdue Fines",
    navAIAnalytics: "AI Demand & Inventory",
    navUsers: "User Directory",
    navLibrarians: "Librarian Staff",
    navSuppliers: "Suppliers & Purchases",
    navReports: "Reports & PDF Export",
    navAuditLogs: "System Audit Logs",
    navSettings: "Library Settings",
    navHealth: "System Health & Mongo",

    // Landing Page
    heroBadge: "Next-Generation AI Library Intelligence",
    heroTitle: "AI-Powered Smart Library Management & Personalized Recommendation System",
    heroDesc: "Designed for modern academic institutions. Featuring real-time circulation tracking, Scikit-learn TF-IDF content filtering, OCR book ingestion, and intelligent demand forecasting.",
    heroSearchPlaceholder: "Search by title, author, ISBN, or topic (e.g., Python, Algorithms)...",
    searchBtn: "Search",
    exploreCatalogBtn: "Explore Library Catalog",
    memberPortalBtn: "Member Portal Sign In",
    askAssistantBtn: "Ask AI Assistant",
    statTitles: "Catalog Titles",
    statCopies: "Physical Copies",
    statMembers: "Active Members",
    statAIScore: "AI Recommender Score",
    verifiedMeta: "100% Verified Metadata",
    barcodedTracked: "Barcoded & Tracked",
    studentsFaculty: "Students & Faculty",
    tfidfModel: "TF-IDF & Cosine Similarity",
    aiArchTitle: "Intelligent Architectural Highlights",
    aiArchSub: "Designed with high cohesion, smart circulation tracking, and TF-IDF machine learning recommendation components.",
    tfidfCardTitle: "TF-IDF & Cosine Similarity",
    tfidfCardDesc: "Vectorizes book titles, descriptions, categories, and syllabus keywords. Generates high-confidence content recommendations matching user borrowing profiles and department curriculum.",
    demandCardTitle: "Predictive Demand Analytics",
    demandCardDesc: "Monitors turnover rates and reservation velocities to alert librarians of potential stock shortages, high-demand titles, and idle inventory before exams approach.",
    ocrCardTitle: "OCR & Barcode Ingestion",
    ocrCardDesc: "Upload book covers or ISBN barcodes to extract standardized metadata automatically with verification modals to prevent data corruption.",
    featuredCatalogTitle: "Featured Academic Catalog",
    featuredCatalogSub: "Top-rated engineering and computer science textbooks.",
    viewAllCatalog: "View All Catalog",
    faqHeading: "Frequently Asked Questions",
    faqSub: "Everything you need to know about Library Management features.",
    footerText: "© 2026 Smart Library Management System. All Rights Reserved.",
    academicProjectNote: "Smart Library Management System",

    // Catalog & Book Detail
    catalogTitle: "Academic Digital Catalog",
    catalogSub: "Explore curated textbooks, technical references, and university course materials.",
    subjectCategory: "Subject Category",
    allCategories: "All Categories",
    availability: "Availability",
    allStatuses: "All Statuses",
    availToBorrow: "Available to Borrow",
    checkedOut: "Currently Checked Out",
    sortBy: "Sort By",
    sortRelevant: "Top Rated & Relevant",
    sortTitle: "Title (A - Z)",
    sortMostBorrowed: "Most Borrowed",
    sortRecent: "Recently Added",
    backToCatalog: "Back to Catalog",
    physicalLocation: "Physical Location",
    copiesInStock: "in stock",
    reservedOut: "Reserved/Out",
    reserveBook: "Reserve Book",
    reserveWaitTime: "Estimated waiting time",
    copiesAvailInStacks: "Copies Available in Stacks",
    reserving: "Reserving...",
    copyInventoryHeader: "Copy Inventory & Physical Status",
    barcode: "Barcode",
    copyNumber: "Copy #",
    condition: "Condition",
    shelfRack: "Shelf / Rack",
    similarBooksTitle: "Similar Books (TF-IDF Content Matched)",
    matchScore: "Match",
    studentReviewsTitle: "Student Reviews & Feedback",
    postReviewBtn: "Post Academic Review",
    yourRating: "Your Academic Rating:",
    reviewPlaceholder: "Share how this book helped your coursework, projects, or thesis research...",

    // Circulation
    circulationTitle: "Circulation Counter & Loan Processing",
    circulationSub: "Issue books, process returns, calculate overdue fines, and manage loan renewals.",
    issueBookTab: "Issue Book",
    returnBookTab: "Return Book",
    activeOverdueLoansTab: "Active & Overdue Loans",
    selectMember: "Select Student / Member *",
    selectAvailBook: "Select Available Book *",
    confirmIssueBtn: "Confirm Book Issue & Print Receipt",
    returnInputLabel: "Transaction ID or Copy Barcode *",
    processReturnBtn: "Process Return & Calculate Fines",
    renewBtn: "Renew",
    returnBtn: "Return",

    // AI & Assistant
    aiRecsTitle: "Personalized AI Recommendations",
    aiRecsSub: "Dynamically generated interest vector based on your curriculum, borrowing history, and syllabus keywords.",
    recommendedForYou: "Recommended For You",
    becauseYouBorrowed: "Because You Borrowed",
    curriculumCore: "Curriculum Core",
    trendingAcrossCampus: "Trending Across Campus",
    aiAssistantTitle: "Smart Library AI Assistant",
    aiAssistantSub: "Connected to Live MongoDB Database",
    aiAssistantGreeting: "Hello! I am your AI Library Assistant. Ask me anything about our academic catalog, live book availability, shelf locations, or personalized book recommendations!",
    aiDemandTitle: "AI Demand Prediction & Inventory Health",
    aiDemandSub: "Automated stock shortage detection, loan turnover rate modeling, and collection health scoring.",
    inventoryHealthScore: "Inventory Health Score",
    utilizationRate: "Average Utilization Rate",
    predictedShortages: "Predicted Shortage Risks",
    idleCopies: "Excess / Idle Copies",
    criticalShortagesTitle: "Critical Shortages & Recommended Acquisitions",

    // Student Workspace
    readingWorkspaceTitle: "Student Academic Reading Workspace",
    readingWorkspaceSub: "Track reading targets, analyze borrowing patterns, and curate course wishlists.",
    totalBooksRead: "Total Books Read",
    currentlyBorrowed: "Currently Borrowed",
    avgReadingSpeed: "Avg. Reading Speed",
    wishlistItems: "Wishlist Items",
    readingChallengesTitle: "Reading Challenges & Academic Milestones",
    newReadingGoalBtn: "New Reading Goal",
    bookmarkedTitles: "My Bookmarked Titles",
    facilityBookingTitle: "Library Facilities & Seat Booking",
    facilityBookingSub: "Reserve quiet individual study carrel pods or collaborative seminar rooms with automated double-booking prevention.",
    bookTimeSlotBtn: "Book Time Slot",
    myActiveBookings: "My Active Facility Reservations",

    // Admin & Ops
    adminHubTitle: "Library Administration & Intelligence Hub",
    adminHubSub: "Real-time circulation metrics, automated fine tracking, and predictive inventory health.",
    circulationDeskBtn: "Circulation Desk",
    ocrScannerBtn: "OCR Book Scanner",
    exportReportsBtn: "Export Reports",
    circulationGrowthTitle: "Circulation Growth & Return Trends",
    deptDemandTitle: "Department & Category Demand",
    masterInventoryTitle: "Master Book Inventory Management",
    addNewBookBtn: "Add New Book",
    batchCSVImportBtn: "Batch CSV Import",
    exportCSVBtn: "Export CSV",
    ocrIngestionTitle: "OCR & ISBN Optical Book Ingestion",
    runOCRBtn: "Run OCR & Extract Metadata",
    confirmSaveMongo: "Confirm & Save to MongoDB Catalog",
    userDirectoryTitle: "Student & Member Directory",
    librarianStaffTitle: "Librarian Staff & Activity Tracking",
    suppliersPurchasesTitle: "Suppliers & Book Acquisitions",
    systemAuditTitle: "System Security & Audit Trail",
    systemSettingsTitle: "System Parameters & Library Policies",
    systemHealthTitle: "System Health & Database Engine Status",

    // Book Management & Cover Photos
    bookTitle: "Book Title",
    isbn: "ISBN",
    primaryAuthor: "Primary Author",
    publisher: "Publisher",
    edition: "Edition",
    pubYear: "Publication Year",
    totalCopies: "Total Copies",
    shelf: "Shelf",
    rack: "Rack",
    row: "Row",
    price: "Price ($)",
    description: "Description",
    coverPhoto: "Book Cover Image",
    autoFetchCover: "Auto-Fetch Cover",
    uploadPhoto: "Upload Photo",
    previewCover: "Cover Preview",
    enterCoverUrl: "Paste Image URL or Auto-Fetch / Upload",
    saveChanges: "Save Changes",
    addBookBtnModal: "Add Book & Generate Barcodes",
    cancel: "Cancel",
    filterPlaceholder: "Filter by title, author, ISBN...",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    duplicate: "Duplicate",
    archive: "Archive",
    restore: "Restore",
    confirmDelete: "Confirm Delete",
    csvDragDrop: "Upload CSV file (.csv) with catalog records",

    // Auth & Modals
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    studentId: "Student ID",
    department: "Department",
    academicYear: "Academic Year",
    loginTitle: "Sign In to Library Management",
    registerTitle: "Student & Faculty Library Registration",
    quickDemoAccounts: "1-Click Quick Demo Login",
    profileTitle: "My Academic Profile & Digital Library Pass",
    personalDetails: "Personal Information",
    profilePicture: "Profile Picture & Avatar",
    uploadFromDevice: "Upload Photo from Device",
    chooseAvatar: "Choose Preset Avatar",
    enterAvatarUrl: "Or Enter Direct Image URL",
    phoneNumber: "Contact Phone Number",
    academicBio: "Academic Bio & Research Focus",
    academicInterests: "Course Interests / Specialization",
    campusAddress: "Campus Hostel / Address",
    preferredLang: "Preferred Language",
    saveProfile: "Save Profile Changes",
    profileSaved: "Profile updated successfully.",
    avatarUpdated: "Profile picture updated successfully.",
    avatarUploadFailed: "Failed to upload profile picture.",
    securityPassword: "Security & Password Management",
    accountSummary: "Central Library Membership Card",
    memberSince: "Member Since",
    totalLoans: "Lifetime Books Borrowed",
    avatarUploading: "Uploading picture..."
  },

  ta: {
    // Topbar & Navigation
    brandName: "நூலக மேலாண்மை",
    brandSubtitle: "ஸ்மார்ட் அறிவு மற்றும் சுழற்சி போர்டல்",
    brandShort: "நூலக போர்டல்",
    toggleNav: "வழிசெலுத்தலை மாற்று",
    askAIAssistant: "AI உதவியாளரிடம் கேளுங்கள்",
    notifications: "அறிவிப்புகள்",
    markAllRead: "அனைத்தையும் படித்ததாகக் குறிக்கவும்",
    noNewNotifications: "புதிய அறிவிப்புகள் இல்லை",
    signIn: "உள்நுழைக",
    joinLibrary: "நூலகத்தில் இணைக",
    signOut: "வெளியேறுக",
    welcomeBack: "மீண்டும் வருக",
    english: "English",
    tamil: "தமிழ்",

    // Roles & Badges
    ADMIN: "நிர்வாகி",
    LIBRARIAN: "நூலகர்",
    STUDENT: "மாணவர்",
    AVAILABLE: "கிடைக்கும்",
    ISSUED: "வழங்கப்பட்டது",
    OVERDUE: "தாமதமானது",
    RETURNED: "திரும்பப் பெறப்பட்டது",
    RESERVED: "முன்பதிவு",
    WAITING: "வரிசையில்",
    READY: "பெறத் தயார்",
    CANCELLED: "ரத்து",
    OUT_OF_STOCK: "கையிருப்பில்லை",
    ACTIVE: "செயலில்",
    INACTIVE: "செயலற்றது",
    PENDING: "நிலுவையில்",
    APPROVED: "ஒப்புதல்",
    PURCHASED: "வாங்கப்பட்டது",
    REJECTED: "நிராகரிப்பு",

    // Sidebar Menus
    navHome: "முகப்பு / சிறப்பம்சங்கள்",
    navCatalog: "நூல் பட்டியல்",
    navRecommendations: "AI பரிந்துரைகள்",
    navAssistant: "AI ஸ்மார்ட் உதவியாளர்",
    navMyReading: "எனது வாசிப்பு & இலக்குகள்",
    navWishlist: "விருப்பப்பட்டியல் & புக்மார்க்குகள்",
    navReservations: "எனது முன்பதிவுகள்",
    navRequests: "நூல் கோரிக்கைகள் & வாக்குகள்",
    navFacilities: "படிப்பு இருக்கை முன்பதிவு",
    navProfile: "எனது சுயவிவரம்",
    navAdminDashboard: "நிர்வாக டாஷ்போர்டு",
    navCirculationHub: "சுழற்சி மையம்",
    navBookMgmt: "புத்தக மேலாண்மை & அட்டைகள்",
    navOCRScanner: "OCR நூல் ஸ்கேனர்",
    navCirculation: "வழங்குதல் / திரும்புதல் / புதுப்பித்தல்",
    navFines: "தாமதக் கட்டணங்கள்",
    navAIAnalytics: "AI தேவை & இருப்பு பகுப்பாய்வு",
    navUsers: "பயனாளர் அடைவு",
    navLibrarians: "நூலகப் பணியாளர்கள்",
    navSuppliers: "வழங்குநர்கள் & கொள்முதல்",
    navReports: "அறிக்கைகள் & PDF ஏற்றுமதி",
    navAuditLogs: "கணினி தணிக்கை பதிவுகள்",
    navSettings: "நூலக அமைப்புகள்",
    navHealth: "கணினி நிலை & மோங்கோ",

    // Landing Page
    heroBadge: "அடுத்த தலைமுறை AI நூலக நுண்ணறிவு",
    heroTitle: "AI-இயங்கும் ஸ்மார்ட் நூலக மேலாண்மை மற்றும் தனிப்பயனாக்கப்பட்ட பரிந்துரை அமைப்பு",
    heroDesc: "நவீன கல்வி நிறுவனங்களுக்காக வடிவமைக்கப்பட்டது. நிகழ்நேர சுழற்சி கண்காணிப்பு, Scikit-learn TF-IDF உள்ளடக்க வடிகட்டுதல், OCR புத்தக பதிவு மற்றும் நுண்ணறிவு தேவை முன்னறிவிப்பு ஆகியவற்றைக் கொண்டுள்ளது.",
    heroSearchPlaceholder: "தலைப்பு, ஆசிரியர், ISBN அல்லது பாடம் மூலம் தேடுங்கள் (எ.கா. Python, Algorithms)...",
    searchBtn: "தேடு",
    exploreCatalogBtn: "நூலகப் பட்டியலை ஆராய்க",
    memberPortalBtn: "உறுப்பினர் உள்நுழைவு",
    askAssistantBtn: "AI உதவியாளரிடம் கேளுங்கள்",
    statTitles: "பட்டியல் தலைப்புகள்",
    statCopies: "உண்மையான பிரதிகள்",
    statMembers: "செயலில் உள்ள உறுப்பினர்கள்",
    statAIScore: "AI பரிந்துரை துல்லியம்",
    verifiedMeta: "100% சரிபார்க்கப்பட்ட மெட்டாடேட்டா",
    barcodedTracked: "பார்கோடு மூலம் கண்காணிக்கப்படுகிறது",
    studentsFaculty: "மாணவர்கள் & பேராசிரியர்கள்",
    tfidfModel: "TF-IDF & கொசைன் ஒற்றுமை",
    aiArchTitle: "நுண்ணறிவு கட்டமைப்பு சிறப்பம்சங்கள்",
    aiArchSub: "ஸ்மார்ட் சுழற்சி மற்றும் TF-IDF இயந்திர கற்றல் பரிந்துரைகளுடன் வடிவமைக்கப்பட்ட நவீன நூலக மேலாண்மை அமைப்பு.",
    tfidfCardTitle: "TF-IDF & கொசைன் ஒற்றுமை",
    tfidfCardDesc: "புத்தக தலைப்புகள், விளக்கங்கள், வகைகள் மற்றும் பாடத்திட்ட முக்கிய வார்த்தைகளை வெக்டரைஸ் செய்கிறது. மாணவர் சுயவிவரங்களுக்கு பொருந்தக்கூடிய பரிந்துரைகளை உருவாக்குகிறது.",
    demandCardTitle: "முன்கணிப்பு தேவை பகுப்பாய்வு",
    demandCardDesc: "தேர்வுகள் நெருங்குவதற்கு முன்பாகவே இருப்பு பற்றாக்குறை மற்றும் அதிக தேவை கொண்ட புத்தகங்கள் குறித்து நூலகர்களை எச்சரிக்கிறது.",
    ocrCardTitle: "OCR & பார்கோடு பதிவு",
    ocrCardDesc: "நிலையான மெட்டாடேட்டாவை தானாக பிரித்தெடுக்க புத்தக அட்டைகள் அல்லது ISBN பார்கோடுகளை பதிவேற்றி சரிபார்க்கவும்.",
    featuredCatalogTitle: "சிறப்பு கல்வி நூல் பட்டியல்",
    featuredCatalogSub: "முன்னணி பொறியியல் மற்றும் கணினி அறிவியல் பாடப்புத்தகங்கள்.",
    viewAllCatalog: "முழு பட்டியலையும் காண்க",
    faqHeading: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    faqSub: "நூலக மேலாண்மை அமைப்பின் அனைத்து அம்சங்கள் பற்றிய விரிவான விவரங்கள்.",
    footerText: "© 2026 ஸ்மார்ட் நூலக மேலாண்மை அமைப்பு. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    academicProjectNote: "ஸ்மார்ட் நூலக மேலாண்மை",

    // Catalog & Book Detail
    catalogTitle: "கல்வி டிஜிட்டல் பட்டியல்",
    catalogSub: "பாடப்புத்தகங்கள், தொழில்நுட்ப குறிப்புகள் மற்றும் பல்கலைக்கழக பாடப் பொருட்களை ஆராயுங்கள்.",
    subjectCategory: "பாடப்பிரிவு வகை",
    allCategories: "அனைத்து பிரிவுகள்",
    availability: "கிடைக்கும் நிலை",
    allStatuses: "அனைத்து நிலைகளும்",
    availToBorrow: "எடுக்கக் கிடைக்கும்",
    checkedOut: "தற்போது கடனாக வழங்கப்பட்டுள்ளது",
    sortBy: "வரிசைப்படுத்து",
    sortRelevant: "சிறந்த மதிப்பீடு & பொருத்தமானவை",
    sortTitle: "தலைப்பு (அ - ஃ)",
    sortMostBorrowed: "அதிகம் எடுக்கப்பட்டவை",
    sortRecent: "சமீபத்தில் சேர்க்கப்பட்டவை",
    backToCatalog: "பட்டியலுக்குத் திரும்பு",
    physicalLocation: "நேரடி இருப்பிடம்",
    copiesInStock: "இருப்பில் உள்ளது",
    reservedOut: "முன்பதிவு / இல்லை",
    reserveBook: "புத்தகத்தை முன்பதிவு செய்",
    reserveWaitTime: "எதிர்பார்க்கப்படும் காத்திருப்பு நேரம்",
    copiesAvailInStacks: "அடுக்கில் பிரதிகள் உள்ளன",
    reserving: "முன்பதிவு செய்யப்படுகிறது...",
    copyInventoryHeader: "பிரதிகள் இருப்பு மற்றும் நேரடி நிலை",
    barcode: "பார்கோடு",
    copyNumber: "பிரதி எண்",
    condition: "நிலை",
    shelfRack: "அலமாரி / ரேக்",
    similarBooksTitle: "ஒத்த புத்தகங்கள் (TF-IDF பொருத்தம்)",
    matchScore: "பொருத்தம்",
    studentReviewsTitle: "மாணவர் மதிப்புரைகள் & பின்னூட்டம்",
    postReviewBtn: "கல்வி மதிப்புரையை இடுகையிடு",
    yourRating: "உங்கள் கல்வி மதிப்பீடு:",
    reviewPlaceholder: "இந்த புத்தகம் உங்கள் பாடநெறி அல்லது ஆராய்ச்சி திட்டத்திற்கு எவ்வாறு உதவியது என்பதைப் பகிரவும்...",

    // Circulation
    circulationTitle: "சுழற்சி கவுண்டர் & கடன் மேலாண்மை",
    circulationSub: "புத்தகங்களை வழங்குங்கள், திரும்புதலை பதிவு செய்யுங்கள், தாமதக் கட்டணங்களை கணக்கிடுங்கள் மற்றும் புதுப்பியுங்கள்.",
    issueBookTab: "புத்தகம் வழங்கு",
    returnBookTab: "புத்தகம் திரும்பு",
    activeOverdueLoansTab: "செயலில் உள்ள & தாமதமான கடன்கள்",
    selectMember: "மாணவர் / உறுப்பினரைத் தேர்ந்தெடுக்கவும் *",
    selectAvailBook: "கிடைக்கும் புத்தகத்தைத் தேர்ந்தெடுக்கவும் *",
    confirmIssueBtn: "புத்தகத்தை வழங்கி ரசீதை அச்சிடு",
    returnInputLabel: "பரிவர்த்தனை எண் அல்லது பார்கோடு *",
    processReturnBtn: "திரும்புதலை பதிவு செய்து கட்டணத்தை கணக்கிடு",
    renewBtn: "புதுப்பி",
    returnBtn: "திரும்பு",

    // AI & Assistant
    aiRecsTitle: "தனிப்பயனாக்கப்பட்ட AI பரிந்துரைகள்",
    aiRecsSub: "உங்கள் பாடத்திட்டம், கடன் வரலாறு மற்றும் முக்கிய வார்த்தைகளின் அடிப்படையில் தானாக உருவாக்கப்பட்ட ஆர்வம்.",
    recommendedForYou: "உங்களுக்காக பரிந்துரைக்கப்படுபவை",
    becauseYouBorrowed: "நீங்கள் கடன் வாங்கியதால் பரிந்துரைக்கப்படுபவை",
    curriculumCore: "பாடத்திட்ட மைய நூல்கள்",
    trendingAcrossCampus: "வளாகத்தில் பிரபலமாக உள்ளவை",
    aiAssistantTitle: "ஸ்மார்ட் நூலக AI உதவியாளர்",
    aiAssistantSub: "நேரடி MongoDB தரவுத்தளத்துடன் இணைக்கப்பட்டுள்ளது",
    aiAssistantGreeting: "வணக்கம்! நான் உங்கள் AI நூலக உதவியாளர். புத்தக கிடைக்கும் நிலை, அலமாரி இருப்பிடம் அல்லது பரிந்துரைகள் பற்றி என்னிடம் கேளுங்கள்!",
    aiDemandTitle: "AI தேவை முன்னறிவிப்பு & இருப்பு நலம்",
    aiDemandSub: "தானியங்கி இருப்பு பற்றாக்குறை கண்டறிதல், சுழற்சி விகித மாதிரி மற்றும் சேகரிப்பு நல மதிப்பீடு.",
    inventoryHealthScore: "இருப்பு நல மதிப்பீடு",
    utilizationRate: "சராசரி பயன்பாட்டு விகிதம்",
    predictedShortages: "கணிக்கப்பட்ட பற்றாக்குறை அபாயங்கள்",
    idleCopies: "அதிகப்படியான / பயன்படாத பிரதிகள்",
    criticalShortagesTitle: "முக்கிய பற்றாக்குறைகள் & பரிந்துரைக்கப்படும் கொள்முதல்",

    // Student Workspace
    readingWorkspaceTitle: "மாணவர் கல்வி வாசிப்பு பணியிடம்",
    readingWorkspaceSub: "வாசிப்பு இலக்குகளை கண்காணிக்கவும், கடன் முறைகளை பகுப்பாய்வு செய்யவும் மற்றும் விருப்பப்பட்டியலை பராமரிக்கவும்.",
    totalBooksRead: "படித்த மொத்த புத்தகங்கள்",
    currentlyBorrowed: "தற்போது கையில் உள்ளவை",
    avgReadingSpeed: "சராசரி வாசிப்பு வேகம்",
    wishlistItems: "விருப்பப்பட்டியல் உருப்படிகள்",
    readingChallengesTitle: "வாசிப்பு சவால்கள் & கல்வி மைல்கற்கள்",
    newReadingGoalBtn: "புதிய வாசிப்பு இலக்கு",
    bookmarkedTitles: "எனது புக்மார்க் செய்யப்பட்ட நூல்கள்",
    facilityBookingTitle: "நூலக வசதிகள் & இருக்கை முன்பதிவு",
    facilityBookingSub: "தனிநபர் படிப்பு அறைகள் அல்லது கருத்தரங்கு அறைகளை இரட்டை முன்பதிவு இன்றி முன்பதிவு செய்யுங்கள்.",
    bookTimeSlotBtn: "நேர இடைவெளியை முன்பதிவு செய்",
    myActiveBookings: "எனது செயலில் உள்ள முன்பதிவுகள்",

    // Admin & Ops
    adminHubTitle: "நூலக நிர்வாகம் & நுண்ணறிவு மையம்",
    adminHubSub: "நிகழ்நேர சுழற்சி அளவீடுகள், தானியங்கி அபராத கண்காணிப்பு மற்றும் முன்கணிப்பு இருப்பு நலம்.",
    circulationDeskBtn: "சுழற்சி கவுண்டர்",
    ocrScannerBtn: "OCR நூல் ஸ்கேனர்",
    exportReportsBtn: "அறிக்கைகளை ஏற்றுமதி செய்",
    circulationGrowthTitle: "சுழற்சி வளர்ச்சி மற்றும் திரும்புதல் போக்குகள்",
    deptDemandTitle: "துறை மற்றும் பிரிவு வாரியான தேவை",
    masterInventoryTitle: "முதன்மை புத்தக இருப்பு மேலாண்மை",
    addNewBookBtn: "புதிய புத்தகத்தை சேர்",
    batchCSVImportBtn: "CSV மொத்த கோப்பு பதிவேற்றம்",
    exportCSVBtn: "CSV ஏற்றுமதி",
    ocrIngestionTitle: "OCR & ISBN ஆப்டிகல் புத்தக பதிவு",
    runOCRBtn: "OCR இயக்கி விவரங்களை பிரித்தெடு",
    confirmSaveMongo: "சரிபார்த்து MongoDB இல் சேமி",
    userDirectoryTitle: "மாணவர் & உறுப்பினர் அடைவு",
    librarianStaffTitle: "நூலகப் பணியாளர்கள் & செயல்பாட்டுக் கண்காணிப்பு",
    suppliersPurchasesTitle: "வழங்குநர்கள் & புத்தகக் கொள்முதல்",
    systemAuditTitle: "கணினி பாதுகாப்பு & தணிக்கை பதிவு",
    systemSettingsTitle: "கணினி அளவுருக்கள் & நூலகக் கொள்கைகள்",
    systemHealthTitle: "கணினி நிலை & தரவுத்தள நிலை",

    // Book Management & Cover Photos
    bookTitle: "புத்தக தலைப்பு",
    isbn: "ISBN சர்வதேச எண்",
    primaryAuthor: "முதன்மை ஆசிரியர்",
    publisher: "பதிப்பகம்",
    edition: "பதிப்பு",
    pubYear: "வெளியீட்டு ஆண்டு",
    totalCopies: "மொத்த பிரதிகள்",
    shelf: "அலமாரி / Stack",
    rack: "ரேக் / Rack",
    row: "வரிசை / Row",
    price: "விலை ($)",
    description: "விவரம் / விளக்கம்",
    coverPhoto: "புத்தக அட்டைப் படம்",
    autoFetchCover: "தானியங்கி அட்டை படம் எடு",
    uploadPhoto: "புகைப்படம் பதிவேற்று",
    previewCover: "அட்டை முன்னோட்டம்",
    enterCoverUrl: "படத்தின் URL ஐ ஒட்டவும் அல்லது தானாகப் பெறவும்",
    saveChanges: "மாற்றங்களைச் சேமி",
    addBookBtnModal: "புத்தகத்தைச் சேர்த்து பார்கோடுகளை உருவாக்கு",
    cancel: "ரத்து செய்",
    filterPlaceholder: "தலைப்பு, ஆசிரியர், ISBN மூலம் வடிகட்டுக...",
    actions: "செயல்கள்",
    edit: "திருத்து",
    delete: "நீக்கு",
    duplicate: "நகலெடு",
    archive: "காப்பகப்படுத்து",
    restore: "மீட்டமை",
    confirmDelete: "நீக்குதலை உறுதிப்படுத்து",
    csvDragDrop: "புத்தக பதிவுகள் கொண்ட CSV கோப்பை பதிவேற்றவும்",

    // Auth & Modals
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்துக",
    fullName: "முழு பெயர்",
    studentId: "மாணவர் பதிவு எண்",
    department: "துறை / பாடம்",
    academicYear: "கல்வி ஆண்டு",
    loginTitle: "நூலக மேலாண்மையில் உள்நுழைக",
    registerTitle: "மாணவர் & பேராசிரியர் நூலக உறுப்பினர் பதிவு",
    quickDemoAccounts: "1-கிளிக் விரைவு மாதிரி உள்நுழைவு",
    profileTitle: "எனது கல்வி சுயவிவரம் & டிஜிட்டல் நூலக அட்டை",
    personalDetails: "தனிப்பட்ட தகவல்கள்",
    profilePicture: "சுயவிவரப் படம் & அவதாரம்",
    uploadFromDevice: "சாதனத்திலிருந்து படம் பதிவேற்று",
    chooseAvatar: "அவதாரத்தைத் தேர்வுசெய்",
    enterAvatarUrl: "நேரடி பட URL ஐ உள்ளிடுக",
    phoneNumber: "தொடர்பு தொலைபேசி எண்",
    academicBio: "கல்வி சுயவிவரக் குறிப்பு & ஆராய்ச்சி ஆர்வம்",
    academicInterests: "விருப்பப் பாடங்கள் & சிறப்புப் புலங்கள்",
    campusAddress: "வளாக விடுதி / முகவரி",
    preferredLang: "விருப்பமான காட்சி மொழி",
    saveProfile: "சுயவிவர மாற்றங்களைச் சேமி",
    profileSaved: "சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.",
    avatarUpdated: "சுயவிவரப் படம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.",
    avatarUploadFailed: "சுயவிவரப் படம் பதிவேற்ற முடியவில்லை.",
    securityPassword: "பாதுகாப்பு & கடவுச்சொல் மேலாண்மை",
    accountSummary: "மத்திய நூலக உறுப்பினர் அட்டை",
    memberSince: "உறுப்பினர் தொடக்கம்",
    totalLoans: "மொத்த கடன் பெற்ற நூல்கள்",
    avatarUploading: "படம் பதிவேற்றப்படுகிறது..."
  }
};

const categoryTamilMap = {
  "Computer Science": "கணினி அறிவியல்",
  "Software Engineering": "மென்பொருள் பொறியியல்",
  "Artificial Intelligence": "செயற்கை நுண்ணறிவு & AI",
  "Data Science": "தரவு அறிவியல் & பகுப்பாய்வு",
  "Distributed Systems": "பகிர்ந்தளிக்கப்பட்ட அமைப்புகள்",
  "Cybersecurity": "வலைப்பின்னல் பாதுகாப்பு",
  "Cloud Computing": "மேகக் கணினி & DevOps",
  "Database Systems": "தரவுத்தள அமைப்புகள்",
  "Web & Mobile Development": "வலை & மொபைல் பயன்பாடுகள்",
  "Algorithms & Complexity": "அல்காரிதம்கள் & கட்டமைப்புகள்",
  "Computer Networks": "கணினி நெட்வொர்க்குகள்",
  "Engineering Mathematics": "பொறியியல் கணிதம்",
  "Electronics & Hardware": "மின்னணுவியல் & வன்பொருள்",
  "Management & Information Systems": "மேலாண்மை தகவல் அமைப்புகள்"
};

const conditionTamilMap = {
  "New": "புதியது",
  "Good": "நன்று",
  "Fair": "சுமாரானது"
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('smartlib_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('smartlib_lang', lang);
  }, [lang]);

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'en' ? 'ta' : 'en'));
  };

  const setLanguage = (newLang) => {
    if (newLang === 'en' || newLang === 'ta') {
      setLang(newLang);
    }
  };

  const t = (key, fallback = '') => {
    if (translations[lang] && translations[lang][key]) {
      return translations[lang][key];
    }
    if (translations['en'] && translations['en'][key]) {
      return translations['en'][key];
    }
    return fallback || key;
  };

  const tCategory = (cat) => {
    if (lang === 'ta' && categoryTamilMap[cat]) {
      return categoryTamilMap[cat];
    }
    return cat;
  };

  const tCondition = (cond) => {
    if (lang === 'ta' && conditionTamilMap[cond]) {
      return conditionTamilMap[cond];
    }
    return cond;
  };

  return (
    <LanguageContext.Provider value={{
      lang,
      toggleLanguage,
      setLanguage,
      t,
      tCategory,
      tCondition,
      isTamil: lang === 'ta'
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
